#!/usr/bin/env bash
# installs nginx and prints Hello World!
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo nginx -t

sudo service nginx start
