#!/usr/bin/env bash
# This script displays 'To infinity and beyond" indefinitely with a sleep 2, then another message when receiving SIGTERm signal

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
