#!/bin/bash
#makes sure that nginx is running as the nginx user
apt-get update
apt-get install -y nginx
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 8080;
	server_name _;

}
EOF

service nginx restart
ps auxff | grep ngin[x]
nc -z 0 8080
